version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
      POSTGRES_DB: coreapi
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"